/*
 * ConfigFrame.java
 *
 * Created on 20. červenec 2007, 18:59
 */

package esmska.gui;

import com.jgoodies.looks.plastic.PlasticLookAndFeel;
import com.jgoodies.looks.plastic.PlasticTheme;
import esmska.*;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.skin.SkinInfo;
import esmska.data.Config;
import esmska.persistence.PersistenceManager;

/** Configure settings form
 *
 * @author  ripper
 */
public class ConfigFrame extends javax.swing.JFrame {
    private static final String RES = "/esmska/resources/";
    private Config config = PersistenceManager.getConfig();
    private boolean fullyInicialized;
    private final String LAF_SYSTEM = "Systémový";
    private final String LAF_CROSSPLATFORM = "Meziplatformní";
    private final String LAF_GTK = "GTK";
    private final String LAF_JGOODIES = "JGoodies";
    private final String LAF_SUBSTANCE = "Substance";
    
    /** Creates new form ConfigFrame */
    public ConfigFrame() {
        initComponents();
        useSenderIDCheckBoxActionPerformed(null);
        tabbedPane.setMnemonicAt(0, KeyEvent.VK_O);
        tabbedPane.setMnemonicAt(1, KeyEvent.VK_H);
        tabbedPane.setMnemonicAt(2, KeyEvent.VK_V);
        tabbedPane.setIconAt(0, new ImageIcon(getClass().getResource(RES + "config-16.png")));
        tabbedPane.setIconAt(1, new ImageIcon(getClass().getResource(RES + "appearance-small.png")));
        tabbedPane.setIconAt(2, new ImageIcon(getClass().getResource(RES + "operators/Vodafone.png")));
        closeButton.requestFocusInWindow();
        
        lafComboBox.setModel(new DefaultComboBoxModel(new String[] {
            LAF_SYSTEM, LAF_CROSSPLATFORM, LAF_GTK, LAF_JGOODIES, LAF_SUBSTANCE}));
        if (config.getLookAndFeel().equals(ThemeManager.LAF_SYSTEM))
            lafComboBox.setSelectedItem(LAF_SYSTEM);
        else if (config.getLookAndFeel().equals(ThemeManager.LAF_CROSSPLATFORM))
            lafComboBox.setSelectedItem(LAF_CROSSPLATFORM);
        else if (config.getLookAndFeel().equals(ThemeManager.LAF_GTK))
            lafComboBox.setSelectedItem(LAF_GTK);
        else if (config.getLookAndFeel().equals(ThemeManager.LAF_JGOODIES))
            lafComboBox.setSelectedItem(LAF_JGOODIES);
        else if (config.getLookAndFeel().equals(ThemeManager.LAF_SUBSTANCE))
            lafComboBox.setSelectedItem(LAF_SUBSTANCE);
        
        updateThemeComboBox();
        
        fullyInicialized = true;
    }
    
    private void updateThemeComboBox() {
        themeComboBox.setEnabled(false);
        String laf = (String) lafComboBox.getSelectedItem();
        
        if (laf.equals(LAF_JGOODIES)) {
            ArrayList<String> themes = new ArrayList<String>();
            for (Object o : PlasticLookAndFeel.getInstalledThemes())
                themes.add(((PlasticTheme)o).getName());
            themeComboBox.setModel(new DefaultComboBoxModel(themes.toArray()));
            themeComboBox.setSelectedItem(config.getLafJGoodiesTheme());
            themeComboBox.setEnabled(true);
        }
        
        else if (laf.equals(LAF_SUBSTANCE)) {
            ArrayList<String> themes = new ArrayList<String>();
            new SubstanceLookAndFeel();
            for (SkinInfo skinInfo : SubstanceLookAndFeel.getAllSkins().values())
                themes.add(skinInfo.getDisplayName());
            themeComboBox.setModel(new DefaultComboBoxModel(themes.toArray()));
            themeComboBox.setSelectedItem(config.getLafSubstanceSkin());
            themeComboBox.setEnabled(true);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        rememberQueueCheckBox = new javax.swing.JCheckBox();
        rememberLayoutCheckBox = new javax.swing.JCheckBox();
        removeAccentsCheckBox = new javax.swing.JCheckBox();
        checkUpdatesCheckBox = new javax.swing.JCheckBox();
        rememberHistoryCheckBox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        lafComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        themeComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        windowDecorationsCheckBox = new javax.swing.JCheckBox();
        windowCenteredCheckBox = new javax.swing.JCheckBox();
        toolbarVisibleCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        useSenderIDCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        senderNumberTextField = new javax.swing.JTextField();
        senderNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nastavení");
        setIconImage(new ImageIcon(getClass().getResource(RES + "config-48.png")).getImage());
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        rememberQueueCheckBox.setMnemonic('f');
        rememberQueueCheckBox.setSelected(config.isRememberQueue());
        rememberQueueCheckBox.setText("Ukládat frontu neodeslaných sms");
        rememberQueueCheckBox.setToolTipText("<html>\nPři ukončení programu uchovává frontu neodeslaných sms pro příští spuštění programu\n</html>");
        rememberQueueCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberQueueCheckBoxActionPerformed(evt);
            }
        });

        rememberLayoutCheckBox.setMnemonic('r');
        rememberLayoutCheckBox.setSelected(config.isRememberLayout());
        rememberLayoutCheckBox.setText("Pamatovat rozvržení formuláře");
        rememberLayoutCheckBox.setToolTipText("<html>\nPoužije aktuální rozměry programu a prvků formuláře při příštím spuštění programu\n</html>");
        rememberLayoutCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberLayoutCheckBoxActionPerformed(evt);
            }
        });

        removeAccentsCheckBox.setMnemonic('d');
        removeAccentsCheckBox.setSelected(config.isRemoveAccents());
        removeAccentsCheckBox.setText("Ze zpráv odstraňovat diakritiku");
        removeAccentsCheckBox.setToolTipText("<html>\nPřed odesláním zprávy z ní odstraní všechna diakritická znaménka\n</html>");
        removeAccentsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAccentsCheckBoxActionPerformed(evt);
            }
        });

        checkUpdatesCheckBox.setMnemonic('n');
        checkUpdatesCheckBox.setSelected(config.isCheckForUpdates());
        checkUpdatesCheckBox.setText("Kontrolovat po startu novou verzi programu");
        checkUpdatesCheckBox.setToolTipText("<html>\nPo spuštění programu zkontrolovat, zda nevyšla novější<br>\nverze programu, a případně upozornit ve stavovém řádku\n</html>");
        checkUpdatesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkUpdatesCheckBoxActionPerformed(evt);
            }
        });

        rememberHistoryCheckBox.setMnemonic('h');
        rememberHistoryCheckBox.setSelected(config.isRememberHistory());
        rememberHistoryCheckBox.setText("Ukládat historii odeslaných sms");
        rememberHistoryCheckBox.setToolTipText("<html>\nPři ukončení programu uchovává historii odeslaných sms pro příští spuštění programu\n</html>");
        rememberHistoryCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberHistoryCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rememberHistoryCheckBox)
                    .addComponent(rememberLayoutCheckBox)
                    .addComponent(rememberQueueCheckBox)
                    .addComponent(removeAccentsCheckBox)
                    .addComponent(checkUpdatesCheckBox))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rememberLayoutCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rememberQueueCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rememberHistoryCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeAccentsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkUpdatesCheckBox)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Obecné", jPanel1);

        lafComboBox.setToolTipText("<html>\nUmožní vám změnit vzhled programu\n</html>");
        lafComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lafComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setDisplayedMnemonic('v');
        jLabel4.setLabelFor(lafComboBox);
        jLabel4.setText("Vzhled:");
        jLabel4.setToolTipText(lafComboBox.getToolTipText());

        jLabel7.setFont(jLabel7.getFont().deriveFont(Font.ITALIC));
        jLabel7.setText("* Pro projevení změn je nutný restart programu!");

        themeComboBox.setToolTipText("<html>\nBarevná schémata pro zvolený vzhled\n</html>");
        themeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setDisplayedMnemonic('m');
        jLabel6.setLabelFor(themeComboBox);
        jLabel6.setText("Motiv:");
        jLabel6.setToolTipText(themeComboBox.getToolTipText());

        windowDecorationsCheckBox.setMnemonic('p');
        windowDecorationsCheckBox.setSelected(config.isLafWindowDecorated());
        windowDecorationsCheckBox.setText("Použít vzhled i na okraje oken *");
        windowDecorationsCheckBox.setToolTipText("<html>\nZda má místo operačního systému vykreslovat<br>\nrámečky oken zvolený vzhled\n</html>");
        windowDecorationsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowDecorationsCheckBoxActionPerformed(evt);
            }
        });

        windowCenteredCheckBox.setMnemonic('u');
        windowCenteredCheckBox.setSelected(config.isStartCentered());
        windowCenteredCheckBox.setText("Spustit program uprostřed obrazovky");
        windowCenteredCheckBox.setToolTipText("<html>Zda-li nechat umístění okna programu na operačním systému,<br>\nnebo ho umístit vždy doprostřed obrazovky</html>");
        windowCenteredCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowCenteredCheckBoxActionPerformed(evt);
            }
        });

        toolbarVisibleCheckBox.setSelected(config.isToolbarVisible());
        toolbarVisibleCheckBox.setText("Zobrazit panel nástrojů");
        toolbarVisibleCheckBox.setToolTipText("<html>\nZobrazit panel nástrojů, který umožňuje rychlejší ovládání myší některých akcí\n</html>");
        toolbarVisibleCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarVisibleCheckBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("*");

        jLabel8.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolbarVisibleCheckBox)
                    .addComponent(windowCenteredCheckBox)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(themeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lafComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addComponent(windowDecorationsCheckBox))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lafComboBox, themeComboBox});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lafComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(themeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(windowDecorationsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(windowCenteredCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolbarVisibleCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lafComboBox, themeComboBox});

        tabbedPane.addTab("Vzhled", jPanel3);

        useSenderIDCheckBox.setMnemonic('p');
        useSenderIDCheckBox.setSelected(config.isUseSenderID());
        useSenderIDCheckBox.setText("Připojovat podpis odesilatele");
        useSenderIDCheckBox.setToolTipText("<html>Při připojení podpisu přijde sms adresátovi ze zadaného čísla<br>\na s daným jménem napsaným na konci zprávy</html>");
        useSenderIDCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useSenderIDCheckBoxActionPerformed(evt);
            }
        });

        jLabel1.setDisplayedMnemonic('l');
        jLabel1.setLabelFor(senderNumberTextField);
        jLabel1.setText("Číslo");

        jLabel2.setText("+420");

        senderNumberTextField.setColumns(9);
        senderNumberTextField.setText((config.getSenderNumber() != null ?
            config.getSenderNumber().replaceFirst("^\\+420", "") : null));
    senderNumberTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            senderNumberTextFieldActionPerformed(evt);
        }
    });

    senderNameTextField.setText(config.getSenderName());
    senderNameTextField.setToolTipText("<html>Při vyplnění jména je připojeno na konec zprávy,<br>\ntakže je sms ve skutečnosti o něco delší</html>");
    senderNameTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            senderNameTextFieldActionPerformed(evt);
        }
    });

    jLabel3.setDisplayedMnemonic('m');
    jLabel3.setLabelFor(senderNameTextField);
    jLabel3.setText("Jméno");
    jLabel3.setToolTipText(senderNameTextField.getToolTipText());

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(useSenderIDCheckBox)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(senderNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(senderNameTextField))))
            .addContainerGap(237, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(useSenderIDCheckBox)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel2)
                .addComponent(senderNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(senderNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(164, Short.MAX_VALUE))
    );

    tabbedPane.addTab("Vodafone", jPanel2);

    closeButton.setMnemonic('z');
    closeButton.setText("Zavřít");
    closeButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            closeButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(closeButton)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeAccentsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAccentsCheckBoxActionPerformed
        config.setRemoveAccents(removeAccentsCheckBox.isSelected());
    }//GEN-LAST:event_removeAccentsCheckBoxActionPerformed
    
    private void windowDecorationsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowDecorationsCheckBoxActionPerformed
        config.setLafWindowDecorated(windowDecorationsCheckBox.isSelected());
    }//GEN-LAST:event_windowDecorationsCheckBoxActionPerformed
    
    private void themeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeComboBoxActionPerformed
        String laf = (String) lafComboBox.getSelectedItem();
        
        if (laf.equals(LAF_JGOODIES))
            config.setLafJGoodiesTheme((String)themeComboBox.getSelectedItem());
        else if (laf.equals(LAF_SUBSTANCE))
            config.setLafSubstanceSkin((String)themeComboBox.getSelectedItem());
    }//GEN-LAST:event_themeComboBoxActionPerformed
    
    private void lafComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lafComboBoxActionPerformed
        if (!fullyInicialized)
            return;
        String laf = (String) lafComboBox.getSelectedItem();
        
        if (laf.equals(LAF_SYSTEM))
            config.setLookAndFeel(ThemeManager.LAF_SYSTEM);
        else if (laf.equals(LAF_CROSSPLATFORM))
            config.setLookAndFeel(ThemeManager.LAF_CROSSPLATFORM);
        else if (laf.equals(LAF_GTK))
            config.setLookAndFeel(ThemeManager.LAF_GTK);
        else if (laf.equals(LAF_JGOODIES))
            config.setLookAndFeel(ThemeManager.LAF_JGOODIES);
        else if (laf.equals(LAF_SUBSTANCE))
            config.setLookAndFeel(ThemeManager.LAF_SUBSTANCE);
        
        updateThemeComboBox();
    }//GEN-LAST:event_lafComboBoxActionPerformed
    
    private void rememberLayoutCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberLayoutCheckBoxActionPerformed
        config.setRememberLayout(rememberLayoutCheckBox.isSelected());
    }//GEN-LAST:event_rememberLayoutCheckBoxActionPerformed
    
    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        senderNameTextFieldActionPerformed(null);
        senderNumberTextFieldActionPerformed(null);
    }//GEN-LAST:event_formWindowLostFocus
    
    private void senderNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senderNameTextFieldActionPerformed
        config.setSenderName(senderNameTextField.getText());
    }//GEN-LAST:event_senderNameTextFieldActionPerformed
    
    private void senderNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senderNumberTextFieldActionPerformed
        config.setSenderNumber("+420" + senderNumberTextField.getText());
    }//GEN-LAST:event_senderNumberTextFieldActionPerformed
    
    private void useSenderIDCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useSenderIDCheckBoxActionPerformed
        senderNameTextField.setEnabled(useSenderIDCheckBox.isSelected());
        senderNumberTextField.setEnabled(useSenderIDCheckBox.isSelected());
        config.setUseSenderID(useSenderIDCheckBox.isSelected());
    }//GEN-LAST:event_useSenderIDCheckBoxActionPerformed
    
    private void rememberQueueCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberQueueCheckBoxActionPerformed
        config.setRememberQueue(rememberQueueCheckBox.isSelected());
    }//GEN-LAST:event_rememberQueueCheckBoxActionPerformed
    
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void checkUpdatesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkUpdatesCheckBoxActionPerformed
        config.setCheckForUpdates(checkUpdatesCheckBox.isSelected());
    }//GEN-LAST:event_checkUpdatesCheckBoxActionPerformed

    private void rememberHistoryCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberHistoryCheckBoxActionPerformed
        config.setRememberHistory(rememberHistoryCheckBox.isSelected());
    }//GEN-LAST:event_rememberHistoryCheckBoxActionPerformed

    private void windowCenteredCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowCenteredCheckBoxActionPerformed
        config.setStartCentered(windowCenteredCheckBox.isSelected());
    }//GEN-LAST:event_windowCenteredCheckBoxActionPerformed

    private void toolbarVisibleCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarVisibleCheckBoxActionPerformed
        config.setToolbarVisible(toolbarVisibleCheckBox.isSelected());
        MainFrame.getInstance().setToolbarVisible(toolbarVisibleCheckBox.isSelected());
    }//GEN-LAST:event_toolbarVisibleCheckBoxActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkUpdatesCheckBox;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox lafComboBox;
    private javax.swing.JCheckBox rememberHistoryCheckBox;
    private javax.swing.JCheckBox rememberLayoutCheckBox;
    private javax.swing.JCheckBox rememberQueueCheckBox;
    private javax.swing.JCheckBox removeAccentsCheckBox;
    private javax.swing.JTextField senderNameTextField;
    private javax.swing.JTextField senderNumberTextField;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JComboBox themeComboBox;
    private javax.swing.JCheckBox toolbarVisibleCheckBox;
    private javax.swing.JCheckBox useSenderIDCheckBox;
    private javax.swing.JCheckBox windowCenteredCheckBox;
    private javax.swing.JCheckBox windowDecorationsCheckBox;
    // End of variables declaration//GEN-END:variables
    
}
