#!/bin/bash

# Create distribution packages from dist directory
# in order to be released

# Dependencies: zip, unix2dos

# trap and exit on error
set -e
trap "echo Packaging failed." ERR

# go to the program directory
cd "`dirname "$0"`"

# usage
if [ $# != 1 -o "$1" = "-h" -o "$1" = "--help" ]; then
    echo "Usage: $0 version_dir"
    echo "Example: $0 esmska-0.1.0"
    exit 1
fi

# create temp dirs
FINALNAME="$1"
TMPDIR=`mktemp -d -t esmska-packaging.XXXX`
mkdir "$TMPDIR/$FINALNAME"

# copy files
cp -r ../dist/* "$TMPDIR/$FINALNAME/"

# convert text files to CRLF for windows users
unix2dos "$TMPDIR/$FINALNAME"/*.txt "$TMPDIR/$FINALNAME"/license/*.txt

# create packages
cd "$TMPDIR"
zip -rq9 "$FINALNAME.zip" "$FINALNAME"
tar c "$FINALNAME" | gzip -9 > "$FINALNAME.tar.gz"

# move packages to current directory
cd "$OLDPWD"
mv "$TMPDIR/$FINALNAME.zip" "$TMPDIR/$FINALNAME.tar.gz" .

# delete temp dirs
rm -rf "$TMPDIR"

