#!/bin/bash

# Create exe launcher for MS Windows

# Dependencies: launch4j

# trap and exit on error
set -e
trap "echo Creating exe failed." ERR

# go to the program directory
cd "`dirname "$0"`"

# run launch4j
launch4j "${PWD}/../launch4j/esmska.xml"

