#!/bin/bash

# Creates a tarball containing POT file and czech PO file
# intended for import in Launchpad Translations

# trap and exit on error
set -e
trap "echo Export failed." ERR

# usage
if [ $# != 1 -o "$1" = "-h" -o "$1" = "--help" ]; then
    echo "Usage: $0 output_tarball"
    echo "Example: $0 lp-esmska.tar.gz"
    exit 1
fi

# get absolute path of output file
FILE=`readlink -f "$1"`

# go to the program directory
cd "`dirname "$0"`"

PODIR="$PWD/../po"

# update translations
./update-translations

cd "$PODIR"

# remove value from translator-credits because of Launchpad bug
mv cs.po cs.po_orig
sed 's/^".*Launchpad Contributions.*"$/""/' cs.po_orig | 
  sed 's/^".*launchpad.net.*"$/""/' > cs.po

# create tarball
tar czf "$FILE" esmska.pot cs.po

mv cs.po_orig cs.po
