#!/bin/bash

# Imports PO files exported from Launchpad to PO directory

# Dependencies: translate-toolkit, gettext, dos2unix, native2ascii

# trap and exit on error
set -e
trap "echo Import failed." ERR

# go to the program directory
cd "`dirname "$0"`"

# usage
if [ $# != 1 -o "$1" = "-h" -o "$1" = "--help" ]; then
    echo "Usage: $0 lp_tarball_with_translations"
    echo "Example: $0 launchpad-export.tar.gz"
    exit 1
fi

PODIR="$PWD/../po"

# create temp dir
TMPDIR=`mktemp -d -t esmska-lp-import.XXXX`

# extract
tar xzf "$1" -C "$TMPDIR"

# copy
cd "$TMPDIR"
for PO in `find . -name 'esmska-*.po'`; do
    FILE=`basename "$PO"`
    LOCALE=${FILE%.po}
    LOCALE=${LOCALE#esmska-}
    if [ "$LOCALE" = "cs" ]; then
        # don't update czech locale from LP, it is managed internally
        continue
    fi
    cp "$PO" "$PODIR/$LOCALE.po"
done

# delete temp dir
rm -r "$TMPDIR"

# update translations
cd "$OLDPWD"
./update-translations
