#!/bin/bash

# Updates POT file from properties files and
# updates PO files to be up to date.

# trap and exit on error 
set -e
trap "echo Updating PO files failed." ERR

# go to the program directory
cd "`dirname "$0"`"

prop2po -P ../src/esmska/resources/l10n.properties ../po/esmska.pot
msgattrib -F ../po/esmska.pot -o ../po/esmska.pot # sort entries by location

for PO in ../po/*.po; do
    if [ "$PO" = "../po/*.po" ]; then	# there was no PO file
	break
    fi
    msgmerge -U --backup=none $PO ../po/esmska.pot
done
