#!/bin/bash

# Update desktop file localization strings from properties files.

# Dependencies: native2ascii

# trap and exit on error
set -e
trap "echo Updating desktop file failed." ERR

# go to the program directory
cd "`dirname "$0"`"

DESKTOP="../resources/esmska.desktop"
L10N="../src/esmska/resources"

# delete old lines
sed -i -r '/^Name|^GenericName|^Comment/d' "$DESKTOP"

# add Name line
CONTENT=`native2ascii -reverse "$L10N"/l10n.properties`
TRANS=`grep ^DesktopFile.name= <<< "$CONTENT" | cut -d = -f 2-`
echo "Name=$TRANS" >> "$DESKTOP"

# add GenericName line
CONTENT=`native2ascii -reverse "$L10N"/l10n.properties`
TRANS=`grep ^DesktopFile.genericName= <<< "$CONTENT" | cut -d = -f 2-`
echo "GenericName=$TRANS" >> "$DESKTOP"

# add Comment line
CONTENT=`native2ascii -reverse "$L10N"/l10n.properties`
TRANS=`grep ^DesktopFile.comment= <<< "$CONTENT" | cut -d = -f 2-`
echo "Comment=$TRANS" >> "$DESKTOP"

TMPFILE=`mktemp -t esmska-desktop.XXXX`

# add localized lines
for FILE in `find "$L10N" -type f -name 'l10n_*.properties'`; do
    BASEFILE=`basename "$FILE"`
    LOCALE=${BASEFILE%.properties}
    LOCALE=${LOCALE#l10n_}
    CONTENT=`native2ascii -reverse "$FILE"`

    # add Name line
    TRANS=`grep ^DesktopFile.name= <<< "$CONTENT" | cut -d = -f 2-`
    if [ -n "$TRANS" ]; then
	    echo "Name[$LOCALE]=$TRANS" >> "$TMPFILE"
    fi
    # add GenericName line
    TRANS=`grep ^DesktopFile.genericName= <<< "$CONTENT" | cut -d = -f 2-`
    if [ -n "$TRANS" ]; then
	    echo "GenericName[$LOCALE]=$TRANS" >> "$TMPFILE"
    fi
    # add Comment line
    TRANS=`grep ^DesktopFile.comment= <<< "$CONTENT" | cut -d = -f 2-`
    if [ -n "$TRANS" ]; then
	    echo "Comment[$LOCALE]=$TRANS" >> "$TMPFILE"
    fi
done

# append localized files
sort "$TMPFILE" >> "$DESKTOP"
rm "$TMPFILE"

