#!/bin/bash

# Update desktop file localization strings from properties files.

# Dependencies: native2ascii

# trap and exit on error
set -e
trap "echo Updating desktop file failed." ERR

# go to the program directory
cd "`dirname "$0"`"

DESKTOP="../resources/esmska.desktop"
L10N="../src/esmska/resources"

# delete old lines
sed -i -r '/^Name|^GenericName|^Comment/d' "$DESKTOP"

# add Name line
CONTENT=`native2ascii -reverse "$L10N"/l10n.properties`
TRANS=`echo "$CONTENT" | grep ^DesktopFile.name= | sed -r 's/^.*?=//'`
echo "Name=$TRANS" >> "$DESKTOP"

for FILE in `find "$L10N" -type f -name 'l10n_*.properties'`; do
    BASEFILE=`basename "$FILE"`
    LOCALE=${BASEFILE%.properties}
    LOCALE=${LOCALE#l10n_}
    
    CONTENT=`native2ascii -reverse "$FILE"`
    TRANS=`echo "$CONTENT" | grep ^DesktopFile.name= | sed -r 's/^.*?=//'`
    if [ -n "$TRANS" ]; then
	    echo "Name[$LOCALE]=$TRANS" >> "$DESKTOP"
    fi
done

# add GenericName line
CONTENT=`native2ascii -reverse "$L10N"/l10n.properties`
TRANS=`echo "$CONTENT" | grep ^DesktopFile.genericName= | sed -r 's/^.*?=//'`
echo "GenericName=$TRANS" >> "$DESKTOP"

for FILE in `find "$L10N" -type f -name 'l10n_*.properties'`; do
    BASEFILE=`basename "$FILE"`
    LOCALE=${BASEFILE%.properties}
    LOCALE=${LOCALE#l10n_}
    
    CONTENT=`native2ascii -reverse "$FILE"`
    TRANS=`echo "$CONTENT" | grep ^DesktopFile.genericName= | sed -r 's/^.*?=//'`
    if [ -n "$TRANS" ]; then
	    echo "GenericName[$LOCALE]=$TRANS" >> "$DESKTOP"
    fi
done

# add Comment line
CONTENT=`native2ascii -reverse "$L10N"/l10n.properties`
TRANS=`echo "$CONTENT" | grep ^DesktopFile.comment= | sed -r 's/^.*?=//'`
echo "Comment=$TRANS" >> "$DESKTOP"

for FILE in `find "$L10N" -type f -name 'l10n_*.properties'`; do
    BASEFILE=`basename "$FILE"`
    LOCALE=${BASEFILE%.properties}
    LOCALE=${LOCALE#l10n_}
    
    CONTENT=`native2ascii -reverse "$FILE"`
    TRANS=`echo "$CONTENT" | grep ^DesktopFile.comment= | sed -r 's/^.*?=//'`
    if [ -n "$TRANS" ]; then
	    echo "Comment[$LOCALE]=$TRANS" >> "$DESKTOP"
    fi
done
